### ISSUE TITLE
change values for minimum session data, length

### ISSUE THREAD

**Issue by noah10** [EmotionCognitionLab/lipbelly#13]
We currently consider any session with less than 360 coherence values (3 minutes worth of data, under ideal circumstances) to be invalid and do not record average coherence for it. Per the latest spec update, this should be reduced to 120 coherence values.

After a set is completed we check the emWave database for any "short" sessions (which are usually invalid or aborted sessions) and delete them. Currently a "short" session is any session less than or equal to five minutes long. Per the latest spec update, this should be changed to delete any sessions less than one minute long.

**Comment by maramather** [comment]
Actually, after our conversation, I've changed my mind and this should be a minimum of 5 min of data to be considered valid for recording coherence.

**Comment by noah10** [comment]
This is in and working - an error message rejecting a session because it only had 553 coherence values (< 600, the amount we would expect to get in 5 minutes).
