### ISSUE TITLE
Apply time-of-day restrictions

### ISSUE THREAD

**Issue by nashiro** [EmotionCognitionLab/lipbelly#15]
The app let me start a session when there isn't enough time left before midnight to finish it.
See my notes on 10/3 - 10/5 in the log: https://docs.google.com/spreadsheets/d/1iPXqdJKZImc0gpr07U8qZcB3DyxzJR9OGnsdj8Q8BAs/edit?pli=1#gid=2097427700

**Comment by noah10** [comment]
This is fixed in version 0.0.8 of the app.

**Comment by nashiro** [comment]
I logged in at 11:45PM and tried to do a meditation practice but the app didn't allow me to do it.
I got the following message: "You don't have enough time to complete another session today. Please come back tomorrow."
