### ISSUE TITLE
Cannot Hear Audio Instructions on Old Lenovo Laptop without earphones/headphones

### ISSUE THREAD

**Issue by choipaul92** [EmotionCognitionLab/lipbelly#18]
Despite putting the laptop's volume on the loudest setting, I couldn't hear the audio instructions on Old Lenovo Laptops (HRVT labeled laptops) without earphone/headphones. I managed to wear headphones but had my right ear half covered to allow for the ear sensor to be attached. 

The new lenovo laptops should be okay (HB labeled laptops/MS labeled laptops @nashiro). Can someone with HB laptops confirm?

Old Lenovo Laptop (mine is HRVT 18)
Windows 10 Pro Education 
Ver 22H2

Note @HyunjooY , I went into "troubleshoot audio" in settings on the laptop and then "Playing Audio". It gave me couple of testing sounds where I had to respond "bad" "good" "I did not hear anything." After a couple rounds, it said "generic audio driver" not fixed

**Comment by choipaul92** [comment]
![Capture](https://github.com/EmotionCognitionLab/lipbelly/assets/89946691/7d2c5a3a-10b9-4436-9f43-5f9c3c0e7f99)

**Comment by nashiro** [comment]
I have a Lenovo laptop labelled MS_01 and just tested app version 0.0.9. All worked well including the audio! I turned the volume all the way up and it was just the right volume for me but other people may like it louder.

**Comment by noah10** [comment]
The recording level of the audio is quite low - on my Mac laptop I have to have the volume near max to be able to hear it reasonably well. If there's any background noise participants may have a hard time getting the volume high enough to hear it.

**Comment by choipaul92** [comment]
We recently had two pilot participants complete their sessions with earphones on & they had no issues with hearing the audio (with the new lenovos). I tested the audio using my old lenovo laptop with headphones & I also didn't have an issue with the volume. Perhaps, for this study we can have all participants use earphones? (this could help with consistency as well). Ofc, no intervention condition wouldn't need it.
