### ISSUE TITLE
Add no-intervention condition 

### ISSUE THREAD

**Issue by nashiro** [EmotionCognitionLab/lipbelly#19]
As discussed in Slack, please add a no-intervention condition to the app.

We ask the no-intervention condition to wear the sensor and record heart rate while they sit quietly and do whatever they like that does not involve head motion (use their phone, computer, read a book, watch TV).

**Comment by noah10** [comment]
This is ready to test in version 0.0.10 of the app.

**Comment by nashiro** [comment]
The control condition was added.
