### ISSUE TITLE
Update text shown on the screen during the 20-min meditation (or control) session

### ISSUE THREAD

**Issue by nashiro** [EmotionCognitionLab/lipbelly#20]
1) Right before meditation, participants currently see:
"Please make sure to:
-plug the USC ear sensor into the laptop
-attach the ear sensor to your earlobe
-sit in a comfortable position in a chair and be ready to start a session"

2) During the entire 20-min session, participants listen to Rael's recording and see the text shown below:
"When you are ready to begin, please press the start button. Please get into a comfortable position on a chair or on a pillow, finding a position with your back and neck upright. Please rest and do not do anything during the portion."

Could you replace #2 with the following?
"Please close your eyes and direct your thoughts to your body sensations" (for the Belly and Lip conditions)
"Please sit quietly since we are recording your pulse. Please feel free to do whatever you like that does not involve head motion." (for the no-intervention control condition)

**Comment by noah10** [comment]
I assume you still want everyone to see "When you are ready to begin, please press the start button"?

**Comment by noah10** [comment]
This is ready to test in version 0.0.10 of the app. All conditions include the "When you are ready to begin, please press the start button" text in addition to the text specified above.

**Comment by nashiro** [comment]
The change was successfully made for the belly condition that I was assigned to.

**Comment by juliana-20** [comment]
The same instructions are shown during the 20-min practice for the control condition as described above.

**Comment by nashiro** [comment]
Just confirmed with a pilot participant in the upper lip-focus condition that the instructions are shown correctly. I'll close this issue.
