### ISSUE TITLE
Add brief description of intervention 

### ISSUE THREAD

**Issue by nashiro** [EmotionCognitionLab/lipbelly#21]
Please add a brief description of each intervention between Slides #1 and #2.
 
Slide #1: "Please make sure to..."
Slides #2: "When you are ready to begin, please press the start button...."

**Belly-focus concentration meditation**
You will be asked to sit quietly to meditate for 20 minutes while your heart rate is recorded. During this time, you will listen to a guided meditation (pre-recorded by a meditation expert) to help you focus on the sensations around the belly. Please remember that it is normal for the mind to wander. When this happens, gently bring your attention back to your belly. 

**Upper lip-focus concentration meditation**
You will be asked to sit quietly to meditate for 20 minutes while your heart rate is recorded. During this time, you will listen to a guided meditation (pre-recorded by a meditation expert) to help you focus on the sensations around the nostrils and upper lip. Please remember that it is normal for the mind to wander. When this happens, gently bring your attention back to the upper lip area. 

**Rest**
You will be asked to sit quietly for 20 minutes while your heart rate is recorded. Please feel free to do whatever you would like to do (e.g., use your phone or computer, read a book, watch TV, listen to music) as long as your activity does not involve head motion.

**Comment by nashiro** [comment]
The change was successfully made for the belly condition that I was assigned to.
I'll check the text for the other conditions when we run a pilot study.

**Comment by noah10** [comment]
It would be best to check the other conditions before we run a pilot - that way if there are problems we can fix them before the pilot, saving ourselves the trouble of updating the master used to create the pilot laptops and updating the laptops of pilot participants.

**Comment by juliana-20** [comment]
While piloting the study, I am seeing the same instructions for the control group as described above.

**Comment by nashiro** [comment]
One of the pilot participants I ran was assigned to the Upper lip-focus condition and the instructions were correct. I'll close this issue.
