### ISSUE TITLE
Don't delete emWave sessions > 4m30s

### ISSUE THREAD

**Issue by noah10** [EmotionCognitionLab/lipbelly#22]
The code currently deletes emWave sessions shorter than five minutes. Since most sessions are supposed to be 20 minutes, this is only a problem in one place: The five minute rest and paced breathing sessions that we do at setup, which can be deleted if they are just a hair too short. Change this limit to 4m30s so we don't delete the legitimate five minute rest and paced breathing sessions.

**Comment by noah10** [comment]
We should also set the average coherence reporting minimum to 4.5 minutes so that we capture the average coherence for the setup breathing.

**Comment by choipaul92** [comment]
Can this be tested using Mind-Body 0.0.11?

**Comment by noah10** [comment]
This sounds like it was an invalid test. Rather than quitting the app, you'll need to remove your ear sensor and let the session completely time out. You should see the message "The session has ended because it has been a long time since the device detected a pulse signal. Please press the start button when you are ready to start over." Once you see that, go into emwave to confirm that (a) the session has been saved and (b) that it is longer than 4m30s. Then go back to the app, start a new session and complete it. Once the app has uploaded your data, go back into emwave and confirm the first session is still there.
