### ISSUE TITLE
Image did not load during Post Image Rating Task

### ISSUE THREAD

**Issue by choipaul92** [EmotionCognitionLab/lipbelly#23]
Juliana reported that a picture did not load for her. Instead she saw a white outline of the picture. This occurred on 10/24/23 around 11:38AM or 11:39AM PST.

**Comment by noah10** [comment]
Unfortunately this is probably going to happen sometimes. We don't currently record when it does; if this information is valuable I can include it as part of the emotional picture rating data.

**Comment by choipaul92** [comment]
@nashiro , what are your thoughts?

**Comment by nashiro** [comment]
This happened during the memory test in Lab Visit 2, right?

**Comment by choipaul92** [comment]
@noah10 , yes. So far it only happened to one pilot participant and it was only on 1 image.

**Comment by choipaul92** [comment]
We (kaoru, Juliana, paul) were not able to reproduce this issue.
