### ISSUE TITLE
Reminder Email for Lab Visit 2

### ISSUE THREAD

**Issue by choipaul92** [EmotionCognitionLab/lipbelly#24]
SUBJECT: Reminder: Lab Visit #2 for Meditation Study – Tomorrow

Dear [Insert First Name],
This is a friendly reminder for your upcoming Lab Visit #2, scheduled for tomorrow, [Insert MM/DD/YEAR], [Insert Day of the Week], at [Insert Time]. **Please remember to bring all your devices tomorrow (i.e. laptop bag, laptop, laptop charger, ear sensor, earphones).**

Please ensure you drink plenty of water today and tomorrow for your blood draw. If you are unable to attend Lab Visit #2, please notify us as soon as possible.

Best regards,
The Meditation Study Team

**Comment by noah10** [comment]
What time and how many days prior to the scheduled visit should this be sent?

**Comment by noah10** [comment]
Never mind - I just noticed the text says "scheduled for tomorrow".

**Comment by noah10** [comment]
Per Kaoru, this should go out at 11AM.

**Comment by choipaul92** [comment]
<img width="780" alt="Screenshot 2023-12-13 at 8 32 50 AM" src="https://github.com/EmotionCognitionLab/lipbelly/assets/89946691/9e38282a-e462-49b2-b85e-bb79703b019e">

I got the email but can we change the subject; I feel that the subject for daily reminders and lab visit 2 reminder are too similar. It took me a while to search for the Lab Visit 2 Reminder Email. 

The following are the current email subjects.

**Daily Reminders Email Subject:** A friendly reminder
**Lab Visit 2 Reminder Email Subject:** Reminder: Lab Visit #2 for Meditation Study Tomorrow

Perhaps: 

**Daily Reminders Email Subject:** A friendly daily reminder 
**Lab Visit 2 Reminder Email Subject:** USC Meditation Study: Lab Visit #2 Tomorrow 

@nashiro , what do you think?

**Comment by noah10** [comment]
Remember that "daily" reminders aren't daily, so we probably shouldn't put that word in the subject - it might confuse people.
________________________________

**Comment by nashiro** [comment]
Paul, Juliana and I pilot tested and received the appointment reminder for visit 2. Paul or Noah, please close this issue.
