### ISSUE TITLE
App doesn't open when we first use it

### ISSUE THREAD

**Issue by nashiro** [EmotionCognitionLab/lipbelly#25]
When participants FIRST logged into the app during Visit 1, the app didn't not open. We went to File --> Exit and re-opened the app, which worked. This was the case for all 6 pilot participants.

**Comment by noah10** [comment]
In order to log in you have to use the app, which means it must have been open. Are you referring to emWave not opening?

**Comment by nashiro** [comment]
After participants clicked the app icon on desktop and entered their email and pwd, the app tried to open. We saw a beige window open with a spinning circle in it. Since the spinning circle was there for a long time and nothing happened, we exited the app and reopened it, which worked (meaning the we saw the first slide with the instructions for 5-min rest).

**Comment by nashiro** [comment]
This issue is not urgent because the app always opened the second time.

**Comment by choipaul92** [comment]
This issue is also present in 1.0.2 version; however, like Kaoru commented it does work when you exit and relaunch the app

**Comment by juliana-20** [comment]
I encountered the same issue again today. App works after exiting and restarting.
