### ISSUE TITLE
Update the description of intervention

### ISSUE THREAD

**Issue by nashiro** [EmotionCognitionLab/lipbelly#28]
Please change the Upper lip-focus concentration meditation instructions (shown in #21) to below:

Belly-focus concentration meditation with slow breathing
You will be asked to sit quietly to meditate for 20 minutes while your heart rate is recorded. During this time, you will listen to a guided meditation (pre-recorded by a meditation expert) to help you focus on the sensations around the belly. You will also be asked to breathe slowly during the entire meditation session. Please remember that it is normal for the mind to wander. When this happens, gently bring your attention back to your belly.

*Note from Paul:
The above instructions should be presented after the slide showing the following text:
Please make sure to:
-plug the USB ear sensor into the laptop
-attach the ear sensor to your earlobe
-sit in a comfortable position in a chair and be ready to start a session

after pressing the “continue” button

**Comment by choipaul92** [comment]
Tested this and confirm that the instructions are updated
