### ISSUE TITLE
hidden "show emWave" feature needed

### ISSUE THREAD

**Issue by nashiro** [EmotionCognitionLab/lipbelly#31]
Please add a "show emwave" hidden feature to the app. When we start the app, it would start emWave, hide emWave, and then we would use the "show emwave" hidden feature to show it again. This feature allows the researcher to monitor the participant's pulse data during the initial 20-min session.

**Comment by choipaul92** [comment]
By pressing Ctrl+Shift+E, it did make emWave pop in front of the meditation study app but once you click on the app, emwave goes in the background (but it is still accessible when pressing the minimize button on the app). The Alt+Tab does bring up the task bar where emWave is accessible. Experimenter can look at the emwave app and app at the same time.

This issue can be closed.
