### ISSUE TITLE
please add the condition name to the instructions

### ISSUE THREAD

**Issue by nashiro** [EmotionCognitionLab/lipbelly#32]
At the beginning of each practice session, the app shows the instructions (i.e., "You will be asked to sit quietly to...). Would it be possible to add the condition name at the top of the instructions as shown below?

**"Belly-focus concentration meditation"**
You will be asked to sit quietly to meditate for 20 minutes while your heart rate is recorded. During this time, you will listen to a guided meditation (pre-recorded by a meditation expert) to help you focus on the sensations around the belly......

**"Belly-focus concentration meditation with slow breathing"**
You will be asked to sit quietly to meditate for 20 minutes while your heart rate is recorded. During this time, you will listen to a guided meditation (pre-recorded by a meditation expert) to help you focus on the sensations around the belly. You will also be asked to breathe slowly during the entire meditation session....

**"No-intervention"**
You will be asked to sit quietly for 20 minutes while your heart rate is recorded...

**Comment by choipaul92** [comment]
Just tested this with shaakhini (1.0.5 dev) and the condition name was on top of the instructions. 

This issue can be closed.
