### ISSUE TITLE
please add another instruction slide

### ISSUE THREAD

**Issue by nashiro** [EmotionCognitionLab/lipbelly#34]
Before showing the instructions (e.g., "Belly-focus concentration meditation" You will be asked to sit quietly to meditate...), could you add a slide including the following text?

"You have been randomly assigned to one of three conditions. Please wait for the experimenter to come and give you further instructions. Please DO NOT press any keys."

Could you then set up a secret key sequence (e.g. Ctrl+Shift+S) for the experimenter to press to move forward to the next slide (i.e., "Belly-focus concentration meditation" You will be asked to sit quietly to meditate...)?

**Comment by noah10** [comment]
Note: This should only happen the very first time the participant uses the software. This will be when they are in the lab getting everything set up.

**Comment by noah10** [comment]
This screen should show up after the "Please make sure to: plug the USB sensor into the laptop", etc. screen. The key sequence is Ctrl+Shift+E. When you press that it will show emWave (see #31 ) as well as advance the user to the next screen. This screen should only show up once. After you see it and press Ctrl+Shift+E it should never show up again.

**Comment by choipaul92** [comment]
I tested this with shaakhini (1.0.5. dev) and ctrl+shift+E did make emWave appear. emWave was also accessible when minimizing the app. 

This issue can be closed.
