### ISSUE TITLE
hide emWave pop-up 

### ISSUE THREAD

**Issue by nashiro** [EmotionCognitionLab/lipbelly#6]
When I opened the app, an emWave window pops up and stays there. I had to manually minimize it. Would it be possible to hide the emWave pop-up because I'm afraid some participants will close it instead of minimizing it? 

Notes: As Noah suggested, I've tried below but got no error message.
- Right-click on the Mind-Body Study icon and choose "Properties". 
- In the dialog window that appears, copy the value in the "Target" field.
- Open a command line prompt.
- Put an ampersand, then a space, then the apostrophe, then paste, then an apostrophe and hit enter.
- This ran the app but there is no error message at the command line prompt.

**Comment by noah10** [comment]
This turned out to be because the Windows username had a space in it. The solution is to make sure that none of the study laptops we hand out have spaces in the Windows username.
