### ISSUE TITLE
Demographics Qualtrics: Put character limit on years of education & overall health question

### ISSUE THREAD

**Issue by choipaul92** [EmotionCognitionLab/lipbelly#9]
I answered 166 for years of education and 88 for overall health questions. It allowed me to progress without any issue.

**Comment by choipaul92** [comment]
Updated Qualtrics.

- Education question ranges from 6 to 30 (for reference HS = 12)
- Health question ranges from 1 to 9

**Comment by noah10** [comment]
If this is fixed please either assign it to someone else to test and give it the "needs testing" label or, if you're 100% confident that it's fixed and that the fix didn't have any undesirable side effects, close it.

**Comment by choipaul92** [comment]
This needs to be tested again. I just fixed Qualtrics for minimum & maximum number of characters to be 2.

**Comment by choipaul92** [comment]
Tested and resolved!
